### ISSUE TITLE
Fallback to textarea if rendering invalid json

### ISSUE THREAD

**Issue by b14r** [novadaemon/filament-pretty-json#1]
Hey! I absolutely love this plugin and it's almost exactly what I needed.
Do you think it could be possible to add a fallback to textarea option in case I try to render a invalid json?

I know it sounds dumb but I'm using the plugin to render some api responses and sometimes they can be a string or xml, or completely null. It shows a `[]` when this is the case.

Maybe it doesnt fit the plugin proposal but I figured it wouldn't hurt to ask.

Thank you again!

**Comment by novadaemon** [comment]
Hi. You mean displaying an alternate value in the block if the JSON format is incorrect? Something like this:

```php
   return $form
            ->schema([
                PrettyJson::make('json')
                    ->fail('JSON format is invalid!')
            ]);

**Comment by novadaemon** [comment]
This is a non editable field

**Comment by b14r** [comment]
Sorry, just saw this. What you mentioned before would work, yes.  I tried tinkering a bit with your code (ealier this year) but was unable to get it working.
